# Dependabot configuration file
version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
